- name: Install packages for PostgreSQL on SLES 15
  when: ansible_facts['distribution_major_version'] == "15"
  zypper:
    name:
    - libxml2-devel
    - gdal-devel
    - proj-devel
    - geos-devel
    - libjson-c-devel
    - libxslt-devel
    - docbook-xsl-stylesheets
    - libprotobuf-c-devel
    - libprotobuf-c1
    - gcc-c++
    - ImageMagick

- name: check if protobuf compile is already there
  stat:
    path: /usr/local/bin/protoc-c
  register: protobuf_installed

- name: check if the protobod source code exists
  stat:
    path: /home/{{ postgres_user }}/protocolbuffers-v3.19.1.tar.gz
  register: source_available

- name: Download the PostGIS source code if it is not already there
  get_url:
    url: https://github.com/protocolbuffers/protobuf/releases/download/v3.19.1/protobuf-cpp-3.19.1.tar.gz
    dest: /home/{{ postgres_user }}/protocolbuffers-v3.19.1.tar.gz
    mode: 0775
    owner: "{{ postgres_user }}"
    group: "{{ postgres_group }}"
  when: source_available.stat.exists == false

- name: extract the sources for protopuf
  shell: cd /home/{{ postgres_user }}; tar -axf protocolbuffers-v3.19.1.tar.gz
  become: yes
  become_user: "{{ postgres_user }}"
  when: protobuf_installed.stat.exists == false

- name: Autogen the protobuf source code
  shell: cd /home/{{ postgres_user }}/protobuf-3.19.1; ./autogen.sh
  become: yes
  become_user: "{{ postgres_user }}"
  when: protobuf_installed.stat.exists == false

- name: Configure the protobuf source code
  shell: cd /home/{{ postgres_user }}/protobuf-3.19.1; ./configure
  become: yes
  become_user: "{{ postgres_user }}"
  when: protobuf_installed.stat.exists == false

- name: Compile the protobuf source code
  shell: cd /home/{{ postgres_user }}/protobuf-3.19.1; make
  become: yes
  become_user: "{{ postgres_user }}"
  when: protobuf_installed.stat.exists == false

- name: Install the protobuf source code
  shell: cd /home/{{ postgres_user }}/protobuf-3.19.1; make install
  become: yes
  become_user: root
  when: protobuf_installed.stat.exists == false

- name: Run ldconfig
  shell: ldconfig
  become: yes
  become_user: root

- name: extract the sources when protoc is not already installed
  shell: ln -s /usr/local/bin/protoc /usr/local/bin/protoc-c
  become: yes
  become_user: root
  when: protobuf_installed.stat.exists == false

- name: Download the protoc-gen-c package
  get_url:
    url: https://download.opensuse.org/repositories/openSUSE:/Leap:/15.2/standard/x86_64/protobuf-c-1.3.2-lp152.1.4.x86_64.rpm
    dest: /home/{{ postgres_user }}/protobuf-c-1.3.2-lp152.1.4.x86_64.rpm
    mode: 0775
    owner: "{{ postgres_user }}"
    group: "{{ postgres_group }}"

- name: Install the protoc-gen-c package
  shell: zypper --no-gpg-checks in -y /home/{{ postgres_user }}/protobuf-c-1.3.2-lp152.1.4.x86_64.rpm
  become: yes
  become_user: root

