{
 "title": "Prometheus MSSQL Exporter Copy",
 "description": "Performance and health metrics for Prometheus MSSQL Exporter running on docker.",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "machine",
    "query": {
     "query": "label_values(mssql_server_info, machine)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(mssql_server_info{machine=\"$machine\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Activity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Instance state",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"$instance\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "State OFFLINE",
     "query": "SELECT mean(\"total\") FROM \"State OFFLINE\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Database properties' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Database properties" }
     ]
    }
   ]
  },
  {
   "title": "Deadlocks",
   "type": "stat",
   "description": "Number of lock requests per second that resulted in a deadlock since last restart",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "delta" ] } },
   "targets": [
    {
     "expr": "mssql_deadlocks{instance=\"$instance\"}",
     "measurement": "State ONLINE",
     "query": "SELECT \"total\" FROM \"State ONLINE\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Database properties' AND $timeFilter",
     "select": [
      [
       { "params": [ "total" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Database properties" }
     ]
    }
   ]
  },
  {
   "title": "Kill Connection Errors",
   "type": "stat",
   "description": "Number of kill connection errors/sec since last restart",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mssql_kill_connection_errors{instance=\"$instance\"}",
     "measurement": "State OFFLINE",
     "query": "SELECT \"total\" FROM \"State OFFLINE\" WHERE \"servername\" =~ /$Instance$/ AND \"type\" = 'Database properties' AND $timeFilter",
     "select": [
      [
       { "params": [ "total" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "Database properties" }
     ]
    }
   ]
  },
  {
   "title": "Connections Errors",
   "type": "stat",
   "description": "Number of user errors/sec since last restart",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mssql_kill_connection_errors{instance=\"$instance\"}",
     "legendFormat": "User errors"
    }
   ]
  },
  {
   "title": "Batch requests/s",
   "type": "gauge",
   "description": "Number of batch executed per sec.",
   "gridPos": { "h": 5, "w": 3, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(mssql_batch_requests{instance=\"$instance\"}[1m]) / 60",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CPU (%)",
     "query": "SELECT mean(\"value\") FROM \"measurement\" WHERE $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "SQL process" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/^$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "CPU usage" }
     ]
    }
   ]
  },
  {
   "title": "Wait time ",
   "type": "gauge",
   "description": "needs to be divide per number of cores",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "increase(Waits{db_waits=\"Wait_S\"}[1m]) / 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Batch requests/s",
   "type": "timeseries",
   "description": "Number of batch executed per sec.",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "increase(mssql_batch_requests{instance=\"$instance\"}[1m]) / 60",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Batch resquests/s",
     "measurement": "CPU (%)",
     "query": "SELECT mean(\"value\") FROM \"measurement\" WHERE $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "SQL process" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "servername", "operator": "=~", "value": "/^$Instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "CPU usage" }
     ]
    }
   ]
  },
  {
   "title": "Waits",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Waits{db_waits=\"Percentage\"}",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Waits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(Waits{db_waits=\"Wait_S\"}[1m]) / 60",
     "legendFormat": "{{WaitType}}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Active Connections",
   "type": "timeseries",
   "description": "Number of active connections",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "mssql_connections{instance=\"$instance\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Active Connections",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Waits",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "expr": "Waits{db_waits=\"Percentage\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last day autogrowth",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "targets": [
    { "expr": "auto_growth_last_day", "legendFormat": "{{DatabaseName}}" }
   ]
  },
  {
   "title": "Read Write Stall Time (ms)",
   "type": "timeseries",
   "description": "Wait time (ms) of stall since last restart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "increase(mssql_io_stall_seconds{instance=\"$instance\"}[1m])",
     "legendFormat": "{{db}},{{operation}}"
    }
   ]
  },
  {
   "title": "Databases Sizes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total DB sizes",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 12, "x": 6, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mssql_db_total_size_megabytes{instance=\"$instance\"}",
     "legendFormat": "{{name}} total size"
    }
   ]
  },
  {
   "title": "Data DB sizes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "mssql_db_data_size_megabytes{instance=\"$instance\"}",
     "legendFormat": "{{name}} total size"
    }
   ]
  },
  {
   "title": "Log DB sizes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "mssql_db_log_size_megabytes{instance=\"$instance\"}",
     "legendFormat": "{{name}} total size"
    }
   ]
  }
 ]
}